env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

language: node_js
node_js: "11"
cache:
  - yarn

stages:
  - name: test
    if: true = false
  - name: deploy-pr
    if: type = pull_request AND fork = false and commit_message !~ /(no-deploy|wip)/
  - name: deploy
    if: branch = master AND type IN (push) AND fork = false
  - name: prune
    if: type = cron

install:
  - yarn

script: yarn eslint .


DEPLOY_TO_S3: &DEPLOY_TO_S3
  before_install:
    - pip install --user awscli
  before_script:
    - yarn run webpack --mode production --output-path $TRAVIS_BUILD_DIR/dist

jobs:
  include:
    - stage: prune
      #before_install:
        #- pip install --user awscli
      script: echo todo, delete files from s3 with no active prs
      rust: stable
    - stage: deploy
      script: aws s3 sync $TRAVIS_BUILD_DIR/dist s3://jerahmeelcosinas.net/
      <<: *DEPLOY_TO_S3
    - stage: deploy-pr
      script: aws s3 sync $TRAVIS_BUILD_DIR/dist "s3://review.jerahmeelcosinas.net/pr-$TRAVIS_PULL_REQUEST"
      <<: *DEPLOY_TO_S3
