dist: xenial

env:
  global:
    # include $HOME/.local/bin for `aws`
    - PATH=$HOME/.local/bin:$PATH

language: rust
rust:
  - precache
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    update: true
    snaps:
      - node

stages:
  - test
  - name: deploy-pr
    # if: pr
  - name: deploy
    if: branch = master AND type IN (push)

cache: 
  - cargo
  - yarn

before_install:
  # wasm-pack
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  # yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn


install:
  - cd $TRAVIS_BUILD_DIR/www && yarn

script: cargo test # temporary until I figure out headless testing in travis

jobs:
  include:
    - stage: precache
      script: true
      rust: stable
    - stage: deploy
      rust: stable
      before_install:
        - pip install --user awscli
      script: 
        - wasm-pack --release
        - cd $TRAVIS_BUILD_DIR/pkg && yarn link
        - cd $TRAVIS_BUILD_DIR/www && yarn link sanisoclem-dev
        - aws s3 sync $TRAVIS_BUILD_DIR/dist s3://jerahmeelcosinas.net/
    - stage: deploy-pr
      rust: stable
      before_install:
        - pip install --user awscli
      script: 
        - wasm-pack --release
        - cd $TRAVIS_BUILD_DIR/pkg && yarn link
        - cd $TRAVIS_BUILD_DIR/www && yarn link sanisoclem-dev && yarn run webpack --mode production --output-path $TRAVIS_BUILD_DIR/dist
        - aws s3 sync $TRAVIS_BUILD_DIR/dist "s3://review.jerahmeelcosinas.net/pr-$TRAVIS_PULL_REQUEST"