[package]
name = "sanisoclem-dev"
version = "0.1.0"
authors = ["Jerahmeel Cosinas <me@jerahmeelcosinas.net>"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
url = "1.7.2"
cfg-if = "0.1.2"
wasm-bindgen = "0.2"

# need this dep to see panic messages in console.error
# however, it's big and should be removed in releases?
console_error_panic_hook = { version = "0.1.1", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.2", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.2"
galvanic-assert = "0.8.7"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
